name: myapp
description: "A new Flutter project."

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  flutter_lints: ^5.0.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/img1.jpg
    - assets/img2.jpg
    - assets/img3.jpg
    - assets/img4.jpg
    - assets/img5.avif
    - assets/scanner.png
